### ISSUE TITLE
Exception in thread Thread-AsyncMsgLogRotate

### ISSUE THREAD

**Issue by CrashTimeV** [11notes/docker-kms#1]
```
Exception in thread Thread-AsyncMsgLogRotate:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/bin/py-kms/pykms_Misc.py", line 131, in receive
    while not (self.is_closed and self.queue.empty()):
                                  ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/queues.py", line 129, in empty
    return not self._poll()
               ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 255, in poll
    self._check_closed()
  File "/usr/local/lib/python3.11/multiprocessing/connection.py", line 137, in _check_closed
    raise OSError("handle is closed")
OSError: handle is closed
```

Docker container stops with that error

**Comment by 11notes** [comment]
Care to post your compose.yaml?

**Comment by ToxaAdmin** [comment]
I have this error to.

name: "kms"
services:
  kms:
    image: "11notes/kms:latest"
    container_name: "kms"
    ports:
      - "1688:1688"    
    environment:
      TZ: Europe/Moscow
    volumes:
      - "./kms-var:/kms/var"
    restart: always
    networks:
      - webproxy

  whodb:
    image: "11notes/whodb:latest"
    container_name: "whodb"
    environment:
      TZ: Europe/Moscow
    volumes:
      - "./kms-var:/whodb/var"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=webproxy"      
      - "traefik.http.routers.winact.entrypoints=https"
      - "traefik.http.routers.winact.rule=Host(`******`)"
      - "traefik.http.routers.winact.tls=true"
      - "traefik.http.routers.winact.tls.certresolver=*****"
      - "traefik.http.services.winact-winact.loadbalancer.server.port=8080"
    networks:
      - webproxy

networks:
  webproxy:
    external: true

**Comment by 11notes** [comment]
thanks for the compose. Is this arm? Can you check with the latest tag sha256:f037f0de05a64b87a64bf18374d70800316d769870db9820a1e904502af74956 again?

**Comment by mfide** [comment]
the owner of the ./kms-var folder should be the user has id:1000. if you let docker to create the folder when it was up, the ownership of the folder would belong to the root. then you got the error above. either create the folder yourself (`mkdir kms-var`) before running the container or use following command "`sudo chown -R 1000:1000 ./kms-var`" when the container is not running.

**Comment by 11notes** [comment]
@ToxaAdmin If you use bind mounts make sure the folder is owned by 1000:1000 before starting the container. Use volumes instead of bind mounts.
