### ISSUE TITLE
Dualstack IPv4/IPv6

### ISSUE THREAD

**Issue by bruor** [11notes/docker-kms#2]
Please add an ability to configure py-kms server so that it can listen for requests on IPv6 in addition to IPv4

https://py-kms.readthedocs.io/en/latest/Usage.html#docker-environment:~:text=is%20WDAGUtilityAccount).-,%2Dd%20or%20%2D%2Ddual%20%3Cbool%3E,-Allows%20listening%20to

**Comment by 11notes** [comment]
Simply set ```KMS_IP: "::"``` as environment variable.
