### ISSUE TITLE
arm64 support

### ISSUE THREAD

**Issue by mfide** [11notes/docker-kms#3]
I try to test this repo on my raspberry pi 5 but getting following error after` docker compose up` command:
`kms The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested`

Does the image support arm64 platforms?

Thanks

**Comment by 11notes** [comment]
My bad, I forgot the correct name in the manifest for multi arch, it's now added again and working as intended. Sorry for the inconvinience: https://hub.docker.com/layers/11notes/kms/latest/images/sha256-aeb41756bc3d49b8bb1716590d9065386c831e03bbf31c34bc76269f8363dccd?context=repo
