### ISSUE TITLE
Manual Control for KMS Verification via Whodb

### ISSUE THREAD

**Issue by loki-y-chen-edu** [11notes/docker-kms#4]
I hope to control whether the device can be verified through Whodb. The idea is to add an additional field that allows manual control over whether KMS verification is permitted.

**Comment by 11notes** [comment]
The KMS server has no ACL by default and I feel adding any sort of ACL goes in the wrong direction. You can implement L4 ACL in front of the KMS to achieve that only certain subnets or IP ranges can use it.
